sudo: required
language: generic 
services :
  - docker 

before_install:
  - docker build -t cosacak/docker-react-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true cosacak/docker-react-test npm run test 